version: 2.1

orbs:
  netsparker: netsparker/scan@dev:alpha

        
workflows:
  scan-workflow:
    jobs:
      scantest:
        executor: ci-base
          - netsparker/scan:
              website_id: 9474e2c4-1ec3-40b0-420c-aa7602ffeb3e
              api_url: https://688c3162.ngrok.io
              scanProfile_id: c6558edc-e37c-4304-1588-aacd02cfea77
              scan_type: FullWithPrimaryProfile
